import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Video from "../components/Video";
import Company from "../components/Company";
import Approuch from "../components/Table/approuch";
import Develop from "../components/Table/develop";
import Develop2 from "../components/Table/develop2";
import Resources from "../components/Table/resources";
import SecondHero from "../components/Hero/second";
import Card from "../components/Card";
import Cards from "../components/Card/cards";
import Footer from "../components/Footer";
import Carousel from "../components/Carousel";

export default function Home(props) {
  return (
    <>
      <div className="bg-bg-back">
        <Header />
        <Hero />
        <Video />
        <Company />
        <Approuch />
        <Develop />
        <Develop2 />
        {/* <SecondHero/> */}
        <h2 className="text-2xl mt-20 text-center font-extrabold text-white">
          QUICK START
        </h2>
        <p className="text-4xl text-center font-extrabold text-white">
          Try it yourself
        </p>
        <p className="text-3xl text-center font-extrabold text-white">
          Select a starter template. Modify your code whenever.
        </p>
        <Card />
        <Card />
        <Resources />

        <div className="relative w-full max-w-7xl mx-auto px-4 lg:px-8 pt-12 pb-12">
          <div className="w-3/4 mx-auto ">
            <h2 className="text-center text-5xl text-white">
              {" "}
              Fully Configurable and Customizable.
            </h2>
            <p className="text-white text-2xl text-center p-10">
              As a general-purpose site builder, Stackbit lets you bring your
              own code, components, styles, and workflows. Stackbit is
              configurable to fit into your existing workflows. Work the way you
              want to with the tools, content platforms, and services you're
              already using - no matter how many pages, editors, developers, or
              websites are involved.
            </p>
          </div>
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            <Cards ongo="#4c57c5" />

            <Cards
              ongo="#4c57c5"
              name="We know youre dying to know to know2"
              zurag="https://www.stackbit.com/images/Getting%20started.svg"
            />

            <Cards
              ongo="#F9F216"
              name="We know youre dying to know to know3"
              zurag="https://www.stackbit.com/images/Discord.svg"
            />
          </div>
        </div>
        <div className="divide-y w-3/4 mx-auto">
          <div></div>
          <div></div>
        </div>
        <Carousel />
        {/* <Footer/> */}

        <Head>
          <title>Stackbit</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </>
  );
}
